{pkgs, ...} :{
    nix = with pkgs; [
      ripgrep
      tree
      lazygit
      jump
      fzf
      git
      duckdb
      shfmt
      jump
      neovim
      terraform
      oh-my-zsh
      texliveFull
      nodejs_20
      uv
      yarn
      typescript
      gh
    ];
    homebrew = {
        brews = [
            "graphviz"
            "swiftlint"
            "entr"
            "zoxide"
            "zig"
            "awscli"
            "fish"
        ];
        casks = [
            "docker"
            "spotify"
            "postman"
            "zoom"
            "whatsapp"
            "amethyst"
            "dash"
            "texshop"
            "trader-workstation"
            "ibkr"
            "raycast"
            "visual-studio-code"
            "skim"
            "bruno"
            "google-chrome"
            "todoist"
            "karabiner-elements"
            "steam"
            "sublime-text"
            "logi-options+"
            "readdle-spark"
            "cursor"
            "jetbrains-toolbox"
            "chatgpt"
            "qgis"
            "active-trader-pro"
            "caffeine"
            "font-hack-nerd-font"
            "virtual-desktop-streamer"
            "wezterm"
            "ollama"
        ];
    };
}
