{pkgs, lib, ...} :{ nix = {
        fishPlugins = with pkgs.fishPlugins; [
            tide
            grc
            done
        ];
        shells = with pkgs; [
            bash
        ];
        utils = with pkgs; [
            curl
            python312Full
            grc
            ripgrep
            tree
            lazygit
            jump
            fzf
            git
            duckdb
            shfmt
            jump
            neovim-unwrapped
            terraform
            nodejs_20
            uv
            yarn
            typescript
            gh
            fd
            jujutsu
            ollama
            wezterm
            clang
            unzip
            go
            lynx
            pass
            gnupg
            mutt-wizard
            isync
            gnused
            markdownlint-cli
            nerd-fonts.commit-mono
            ruff
            typst
            typstyle
            zellij
            nix-search-cli
            just
            (lib.mkIf pkgs.stdenv.isLinux pkgs.strace)
        ];
    };
    homebrew = {
        brews = [
            "graphviz"
            "swiftlint"
            "entr"
            "zoxide"
            "zig"
            "awscli"
            "spotify_player"
            "yazi"
            "llama.cpp"
            "huggingface-cli"
            "asitop"
        ];
        casks = [
            "slack"
            "akiflow"
            "docker"
            "spotify"
            "postman"
            "zoom"
            "whatsapp"
            "amethyst"
            "dash"
            "texshop"
            "trader-workstation"
            "ibkr"
            "raycast"
            "visual-studio-code"
            "skim"
            "bruno"
            "google-chrome"
            "todoist"
            "karabiner-elements"
            "steam"
            "sublime-text"
            "logi-options+"
            "cursor"
            "jetbrains-toolbox"
            "chatgpt"
            "qgis"
            "active-trader-pro"
            "caffeine"
            "font-hack-nerd-font"
            "virtual-desktop-streamer"
        ];
    };
}
