# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """$character"""
right_format = """$all"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ → ](bold bg:green fg:black)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_symbol = '[ | ](bold bg:red fg:black)'
vimcmd_replace_one_symbol = '[ r ](bold bg:purple fg:black)'
vimcmd_replace_symbol = '[ r ](bold bg:purple fg:black)'
vimcmd_visual_symbol = '[ v ](bold bg:yellow fg:black)'

[time]
disabled = false
